title:  Soy Ana y esta es mi pagina web de puta mierda 
description: soy la mejor del mundo y por eso teneis que meteros ami pagina web:) (!QUIEN NO DE META ES GAYÂ¡)
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
