title: ""
description: 
title: Centro educativo Nestra se√±ora de la salceda
description: pagina creada con jekyll y Github Pages
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
